CREATE TABLE StudentTable (
    student_id INT PRIMARY KEY,
    student_name VARCHAR(50),
    grade INT,
    major VARCHAR(50),
    is_active BOOLEAN
);

INSERT INTO StudentTable (student_id, student_name, grade, major, is_active) VALUES
(1, 'Aarav Sharma', 10, 'Science', true),
(2, 'Priya Verma', 12, 'Commerce', true),
(3, 'Rahul Kapoor', 11, 'Humanities', false),
(4, 'Anika Patel', 10, 'Science', true),
(5, 'Aryan Singh', 12, 'Commerce', false),
(6, 'Diya Yadav', 11, 'Humanities', true),
(7, 'Kiran Kumar', 9, 'Science', true),
(8, 'Meera Malhotra', 11, 'Commerce', false),
(9, 'Rohan Gupta', 12, 'Humanities', true),
(10, 'Sneha Joshi', 10, 'Science', false),
(11, 'Vikram Verma', 11, 'Commerce', true),
(12, 'Ishika Sharma', 12, 'Humanities', false),
(13, 'Arjun Kapoor', 10, 'Science', true),
(14, ' சாருலதா  Priya', 11, 'Commerce', true),
(15, 'விநாயகர்  Singh', 12, 'Humanities', false),
(16, 'Krishnan Yadav', 9, 'Science', true),
(17, 'Deepika Patel', 10, 'Commerce', false),
(18, 'Siddharth Gupta', 11, 'Humanities', true),
(19, 'Aishwarya Joshi', 12, 'Science', false),
(20, 'రణధీర్  Verma', 10, 'Commerce', true),
(21, 'Sanjana Sharma', 11, 'Humanities', false),
(22, 'Pranav Kapoor', 12, 'Science', true),
(23, 'Nisha Patel', 10, 'Commerce', true),
(24, 'Kunal Singh', 11, 'Humanities', false),
(25, 'க்கியாரா  Yadav', 9, 'Science', true),
(26, 'Manish Kumar', 11, 'Commerce', false),
(27, 'Trisha Malhotra', 12, 'Humanities', true),
(28, 'Rajat Gupta', 10, 'Science', false),
(29, ' Kavya Joshi', 11, 'Commerce', true),
(30, 'Ishan Verma', 12, 'Humanities', false),
(31, 'Ananya Sharma', 10, 'Science', true),
(32, 'Dev Kapoor', 11, 'Commerce', true),
(33, ' சாஹித்யா  Patel', 12, 'Humanities', false),
(34, 'Soham Singh', 9, 'Science', true),
(35, ' ரித்திகா  Yadav', 11, 'Commerce', false),
(36, 'Yuvraj Kumar', 12, 'Humanities', true),
(37, 'Siya Malhotra', 10, 'Science', false),
(38, 'Vivaan Gupta', 11, 'Commerce', true),
(39, 'Diya Joshi', 12, 'Humanities', false),
(40, 'Reyansh Verma', 10, 'Science', true);

SELECT * FROM StudentTable;
